#!/bin/sh

# doit
#
# Run basic ratman tests and update the ratman installation.

raco test .
if test $? -ne 0; then
    echo "ratman test failed... installing cancelled..."
    exit 1
fi
raco pkg remove ratman
raco pkg create --binary `pwd`
raco pkg install ./ratman.zip
